### ISSUE TITLE
Available code

### ISSUE THREAD

**Issue by psj8422** [hehaodele/circuit-gnn#1]
Dear all,  I'm really interested in this paper, wondering schedule to upload the code :)

**Comment by JarvisKevin** [comment]
waiting!!!

**Comment by hehaodele** [comment]
Oh my god. I had kept delaying the code release for so long! Really sorry about that. Please email me if you are still interested in the code such that I can send you the code. Hoping I can clean to code and release it soon during this COVID period.

**Comment by hehaodele** [comment]
Released!
