### ISSUE TITLE
Data collection in CST

### ISSUE THREAD

**Issue by majiteng** [hehaodele/circuit-gnn#2]
Hi Hao He,

I am very interested in this work. Could you let me know how do you collect such a large amount of data from CST?

Best
Jiteng

**Comment by majiteng** [comment]
Solved it, thanks

**Comment by YY-WW518** [comment]
> Solved it, thanks

How do you solve it?

**Comment by majiteng** [comment]
> > Solved it, thanks
> 
> How do you solve it?

I am not using CST. I use Keysight ADS. I suppose the process should be similar.
1. Add a Data Access Component to import the variables list
2. Add a Parameter Sweep function and sweep the variables imported from the Data Access
3. Simulate your circuit model and save the response data you are caring about.
Hope it helps

**Comment by Johhnyzhang** [comment]
Hello, can you give more details about the data generation from Keysight ADS?
